### PR TITLE
Add libzeug dependency

### PR DESCRIPTION
**Pull request by mjendruk**

### CODE REVIEW

**Comment by j-o** [comment]
If gloperate officially depends on libzeug now, the `Signal` duplicate should be removed.

**Comment by scheibel** [comment]
That is a declared design goal :laughing:

**Comment by sbusch42** [comment]
I still think that it would be cleaner and better to just derive Painter from reflectionzeug::Object. That would make the intention clear that a Painter "is an object that can describe itself (in terms of properties and functions) => reflection", rather than "having a pointer to a property group that exists somewhere else". Also, if we go this route, we have to do the same later for functions, which is important for scripting, because this only allows for exposing properties, not functions.

**Comment by scheibel** [comment]
:shipit:?
:ship:!

**Pull request merged**
